from dotenv import load_dotenv
load_dotenv()

from starter_app import app, db
from starter_app.models import User, City, Landlord, Review

with app.app_context():
  db.drop_all()
  db.create_all()

  #Users
  ian = User(username = 'Ian', email = 'ian@aa.io', password = 'password', city_id=1)
  javier = User(username='Javier', email='javier@aa.io', password='password', city_id=2)
  dean = User(username='Dean', email='dean@aa.io', password='password', city_id=3)
  angela = User(username='Angela', email='angela@aa.io', password='password', city_id=1)
  soonmi = User(username='Soon-Mi', email='soonmi@aa.io', password='password', city_id=2)
  alissa = User(username='Alissa', email='alissa@aa.io', password='password', city_id=3)

  #City
  los_angeles = City(cityName='Los Angeles')
  new_york = City(cityName='New York')
  boston = City(cityName='Boston')
  san_francisco = City(cityName='San Franciso')
  chicago = City(cityName='Chicago')
  miami = City(cityName='Miami')

  #Landlords
  
  
  bart_simpson = Landlord(fullName='Bart Simpson', city_id=1)
  kanye_west = Landlord(fullName='Kanye West', city_id=1)
  steve_jobs = Landlord(fullName='Steve Jobs', city_id=1)
  ariyah_mercer = Landlord(fullName='Ariyah Mercer', city_id=1)
  alya_plant = Landlord(fullName='Alya Plant', city_id=1)
  marni_macdonald = Landlord(fullName='Marni Macdonald', city_id=1)
  eshaal_harding = Landlord(fullName='Eshaal Harding', city_id=1)
  moses_klein = Landlord(fullName='Moses Klein', city_id=1)
  brendan_mustafa = Landlord(fullName='Brendan Mustafa', city_id=1)
  ruby_mae_parks = Landlord(fullName='Ruby Mae Parks', city_id=1)
  charlotte_mansell = Landlord(fullName='Charlotte Mansell', city_id=1)
  rajveer_barajas = Landlord(fullName='Rajveer Barajas', city_id=1)
  candice_peacock = Landlord(fullName='Candice Peacock', city_id=1)
  debra_pickett = Landlord(fullName='Debra Pickett', city_id=1)
  donkey_kong = Landlord(fullName='Donkey Kong', city_id=1)
  frank_gallagher = Landlord(fullName='Frank Gallagher', city_id=1)
  charlotte_mansell = Landlord(fullName='Charlotte Mansell', city_id=1)
  greg_gregson = Landlord(fullName='Greg Gregson', city_id=1)
  henry_benson = Landlord(fullName='Henry Benson', city_id=1)
  iggy_pop = Landlord(fullName='Iggy Pop', city_id=1)
  isaiah_johnson = Landlord(fullName='Isaiah Johnson', city_id=1)
  jeff_povey = Landlord(fullName='Jeff Povey', city_id=1)
  joshua_baloney = Landlord(fullName='Joshua Baloney', city_id=1)
  jeb_bush = Landlord(fullName='Jeb Bush', city_id=1)
  jack_hammer = Landlord(fullName='Jack Hammer', city_id=1)
  kristin_kristopherson = Landlord(fullName='Kristin Kristopherson', city_id=1)
  kelly_roastbeef = Landlord(fullName='Kelly Roastbeef', city_id=1)
  kansas_tansas = Landlord(fullName='Kansas Tansas', city_id=1)
  lorrie_cervantes = Landlord(fullName='Lorrie Cervantes', city_id=1)
  mikey_figueroa = Landlord(fullName='Mikey Figueroa', city_id=1)
  michael_hughes = Landlord(fullName='Michael Hughes', city_id=1)
  my_mom = Landlord(fullName='My Mom', city_id=1)
  mansrader_kelly = Landlord(fullName='Mansrader Kelly', city_id=1)
  mick_thompson = Landlord(fullName='Mick Thompson', city_id=1)
  niall_horan = Landlord(fullName='Niall Horan', city_id=1)
  nick_menza = Landlord(fullName='Nick Menza', city_id=1)
  naruto_shippuden = Landlord(fullName='Naruto Shippuden', city_id=1)
  nick_sebastian = Landlord(fullName='Nick Sebastian', city_id=1)
  omar_dilly = Landlord(fullName='Omar Dilly', city_id=1)
  oscar_the_grouch = Landlord(fullName='Oscar the Grouch', city_id=1)
  peanut_man = Landlord(fullName='Peanut Man', city_id=1)
  phillip_johnson = Landlord(fullName='Phillip Johnson', city_id=1)
  philandro_peterson = Landlord(fullName='Philandro Peterson', city_id=1)
  peter_ramirez = Landlord(fullName='Peter Ramirez', city_id=1)
  quinn_rodriguez = Landlord(fullName='Quinn Rodriguez', city_id=1)
  questlove = Landlord(fullName='Questlove', city_id=1)
  terry_rix = Landlord(fullName='Terry Rix', city_id=1)
  timothy_obrien = Landlord(fullName='Timothy O\'brien', city_id=1)
  undertaker = Landlord(fullName='Undertaker', city_id=1)
  wesley_nestle = Landlord(fullName='Wesley Nestle', city_id=1)
  will_hartley = Landlord(fullName='Will Hartley', city_id=1)
  weston_smith = Landlord(fullName='Weston Smith', city_id=1)
  xavier_fletcher = Landlord(fullName='Xavier Fletcher', city_id=1)
  xletal_jefferson = Landlord(fullName='Xletal Jefferson', city_id=1)
  yao_ming = Landlord(fullName='Yao Ming', city_id=1)
  zara_idk = Landlord(fullName='Zara I\'m running out of names', city_id=1)
  zeke_zekerson = Landlord(fullName='Zeke Zekerson', city_id=1)
  zack_pu = Landlord(fullName='Zack Pu', city_id=1)
  

  john_johnson = Landlord(fullName='John Johnson', city_id=2)
  gandalf = Landlord(fullName='Gandalf', city_id=2)
  corey_wagner = Landlord(fullName='Corey Wagner', city_id=2)
  kanye_east = Landlord(fullName='Kanye East', city_id=3)
  michael_scott = Landlord(fullName='Michael Scott', city_id=3)
  bark_bedlinksy = Landlord(fullName='Bark Bedlinsky', city_id=3)
  lukasz_byrd = Landlord(fullName='Lukasz Byrd', city_id=3)
  roan_potts = Landlord(fullName='Roan Potts', city_id=3)

  frazer_hutton = Landlord(fullName='Frazer Hutton', city_id=3)

  #Reviews
  review1 = Review(rating=1, title='The worst landlord', content='Would not turn on the heat in the winter', landlord_id= 1, user_id=1)
  review2 = Review(rating=1, title='Terrible', content='Stole my security deposit!', landlord_id=1, user_id=2)
  review3 = Review(rating=3, title='Ok', content='Cool guy', landlord_id=3, user_id=3)

  db.session.add(ian)
  db.session.add(javier)
  db.session.add(dean)
  db.session.add(angela)
  db.session.add(soonmi)
  db.session.add(alissa)

  db.session.add(los_angeles)
  db.session.add(new_york)
  db.session.add(boston)
  db.session.add(san_francisco)
  db.session.add(chicago)
  db.session.add(miami)
  
  db.session.add(bark_bedlinksy)
  db.session.add(john_johnson)
  db.session.add(bart_simpson)
  db.session.add(kanye_west)
  db.session.add(kanye_east)
  db.session.add(michael_scott)
  db.session.add(gandalf)
  db.session.add(steve_jobs)
  db.session.add(ariyah_mercer)
  db.session.add(lukasz_byrd)
  db.session.add(roan_potts)
  db.session.add(corey_wagner)
  db.session.add(alya_plant)
  db.session.add(marni_macdonald)
  db.session.add(frazer_hutton)
  db.session.add(eshaal_harding)
  db.session.add(moses_klein)
  db.session.add(brendan_mustafa)
  db.session.add(ruby_mae_parks)
  db.session.add(charlotte_mansell)
  db.session.add(rajveer_barajas)
  db.session.add(candice_peacock)
  db.session.add(debra_pickett)
  db.session.add(frank_gallagher)
  db.session.add(charlotte_mansell)
  db.session.add(greg_gregson)
  db.session.add(henry_benson)
  db.session.add(iggy_pop)
  db.session.add(isaiah_johnson)
  db.session.add(jeff_povey)
  db.session.add(joshua_baloney)
  db.session.add(jeb_bush)
  db.session.add(jack_hammer)
  db.session.add(kristin_kristopherson)
  db.session.add(kelly_roastbeef)
  db.session.add(kansas_tansas)
  db.session.add(lorrie_cervantes)
  db.session.add(mikey_figueroa)
  db.session.add(michael_hughes)
  db.session.add(my_mom)
  db.session.add(mansrader_kelly)
  db.session.add(mick_thompson)
  db.session.add(nick_menza)
  db.session.add(naruto_shippuden)
  db.session.add(nick_sebastian)
  db.session.add(oscar_the_grouch)
  db.session.add(peanut_man)
  db.session.add(phillip_johnson)
  db.session.add(philandro_peterson)
  db.session.add(peter_ramirez)
  db.session.add(quinn_rodriguez)
  db.session.add(questlove)
  db.session.add(terry_rix)
  db.session.add(timothy_obrien)
  db.session.add(undertaker)
  db.session.add(wesley_nestle)
  db.session.add(will_hartley)
  db.session.add(weston_smith)
  db.session.add(xavier_fletcher)
  db.session.add(xletal_jefferson)
  db.session.add(yao_ming)
  db.session.add(zara_idk)
  db.session.add(zeke_zekerson)
  db.session.add(zack_pu)
  db.session.add(donkey_kong)

  db.session.add(review1)
  db.session.add(review2)
  db.session.add(review3)

  db.session.commit()
